//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AutolineasFacturas.Modelo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ConexionEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ConexionEntities usando la cadena de conexión encontrada en la sección 'ConexionEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ConexionEntities() : base("name=ConexionEntities", "ConexionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ConexionEntities.
        /// </summary>
        public ConexionEntities(string connectionString) : base(connectionString, "ConexionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ConexionEntities.
        /// </summary>
        public ConexionEntities(EntityConnection connection) : base(connection, "ConexionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<conexiones_servidores> conexiones_servidores
        {
            get
            {
                if ((_conexiones_servidores == null))
                {
                    _conexiones_servidores = base.CreateObjectSet<conexiones_servidores>("conexiones_servidores");
                }
                return _conexiones_servidores;
            }
        }
        private ObjectSet<conexiones_servidores> _conexiones_servidores;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet conexiones_servidores. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToconexiones_servidores(conexiones_servidores conexiones_servidores)
        {
            base.AddObject("conexiones_servidores", conexiones_servidores);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConexionModel", Name="conexiones_servidores")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class conexiones_servidores : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto conexiones_servidores.
        /// </summary>
        /// <param name="id_conexion">Valor inicial de la propiedad id_conexion.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="contrasenia">Valor inicial de la propiedad contrasenia.</param>
        /// <param name="puerto">Valor inicial de la propiedad puerto.</param>
        /// <param name="servidor">Valor inicial de la propiedad servidor.</param>
        public static conexiones_servidores Createconexiones_servidores(global::System.Int32 id_conexion, global::System.String usuario, global::System.String contrasenia, global::System.Int32 puerto, global::System.String servidor)
        {
            conexiones_servidores conexiones_servidores = new conexiones_servidores();
            conexiones_servidores.id_conexion = id_conexion;
            conexiones_servidores.usuario = usuario;
            conexiones_servidores.contrasenia = contrasenia;
            conexiones_servidores.puerto = puerto;
            conexiones_servidores.servidor = servidor;
            return conexiones_servidores;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_conexion
        {
            get
            {
                return _id_conexion;
            }
            set
            {
                if (_id_conexion != value)
                {
                    Onid_conexionChanging(value);
                    ReportPropertyChanging("id_conexion");
                    _id_conexion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_conexion");
                    Onid_conexionChanged();
                }
            }
        }
        private global::System.Int32 _id_conexion;
        partial void Onid_conexionChanging(global::System.Int32 value);
        partial void Onid_conexionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sucursal
        {
            get
            {
                return _sucursal;
            }
            set
            {
                OnsucursalChanging(value);
                ReportPropertyChanging("sucursal");
                _sucursal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sucursal");
                OnsucursalChanged();
            }
        }
        private global::System.String _sucursal;
        partial void OnsucursalChanging(global::System.String value);
        partial void OnsucursalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String base_datos
        {
            get
            {
                return _base_datos;
            }
            set
            {
                Onbase_datosChanging(value);
                ReportPropertyChanging("base_datos");
                _base_datos = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("base_datos");
                Onbase_datosChanged();
            }
        }
        private global::System.String _base_datos;
        partial void Onbase_datosChanging(global::System.String value);
        partial void Onbase_datosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasenia
        {
            get
            {
                return _contrasenia;
            }
            set
            {
                OncontraseniaChanging(value);
                ReportPropertyChanging("contrasenia");
                _contrasenia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasenia");
                OncontraseniaChanged();
            }
        }
        private global::System.String _contrasenia;
        partial void OncontraseniaChanging(global::System.String value);
        partial void OncontraseniaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 puerto
        {
            get
            {
                return _puerto;
            }
            set
            {
                OnpuertoChanging(value);
                ReportPropertyChanging("puerto");
                _puerto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("puerto");
                OnpuertoChanged();
            }
        }
        private global::System.Int32 _puerto;
        partial void OnpuertoChanging(global::System.Int32 value);
        partial void OnpuertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String servidor
        {
            get
            {
                return _servidor;
            }
            set
            {
                OnservidorChanging(value);
                ReportPropertyChanging("servidor");
                _servidor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("servidor");
                OnservidorChanged();
            }
        }
        private global::System.String _servidor;
        partial void OnservidorChanging(global::System.String value);
        partial void OnservidorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();

        #endregion

    
    }

    #endregion

    
}
